#encoding: utf-8

# TeamMember.create!(title: "Principal", bio: "was an angel investor and involved early-on in building Yokayo Biofuels, California's first waste-oil biodiesel production facility.  Sam has spent the last seven years as a consultant and executive coach.  He has a master degree in Industrial and Organizational Psychology and has been leading the preliminary stages of this company for the past year and a half, after meeting Brian Eberly while commuting to Yokayo Biofuels where Sam was coaching the CEO.", first_name: "Sam", last_name: "Roberts")
# TeamMember.create!(title: "Principal – Technology", bio: "has developed the conceptual engineering for the technology.  Brian is currently Chief Operating Officer of Yokayo Biofuels, a producer and distributor of bio-diesel made from waste cooking oils.  Brian began research and analysis of the concept for this plant as the thesis of his master of engineering degree program and has continued to refining the engineering analysis of the concept for over seven years.", first_name: "Brian", last_name: "Eberly")
# TeamMember.create!(title: "Principal", bio: "has 25 years of experience in the development, regulation and financing of alternative energy systems. Roy is an attorney with extensive experience in negotiating power sales and fuel supply agreements, obtaining environmental and land use approvals for projects and in leading project development from conception to operation.  He has founded two companies in the alternative energy space with successful exits from both and led the development of a $300 million waste fuel technology power plant in Australia.", first_name: "Roy", last_name: "Alper")
# HomeStatement.create!(phrase: "At ReBio we reduce emissions through the re-purposing of agricultural waste.")
# HomeStatement.create!(phrase: "Our energy system reduces operating costs and helps California meet carbon reduction standards.")
# HomeStatement.create!(phrase: "We follow the lifecycle value chain of agricultural waste.")

Faq.create!(question: "What is pomace?", answer: "Pomace is left over grape skins and seeds after the winemaking process. Pomace is usually composted in large “windrows” in winegrowing regions throughout the world.  There is latent energy remaining in grape skins that could be captured instead of decomposing in the compost pile (contributing to greenhouse gas emissions).")
Faq.create!(question: "What kind of energy will you be producing?", answer: "Sustainable ethanol from the remaining sugar in the pomace, called “Advanced Biofuel” in the United States. <br> Sustainable electricity made from the syngas that is created in the gasification process.")
Faq.create!(question: "What is currently being done with pomace?", answer: "Most of the pomace in winegrowing regions is composted and actually contributes to greenhouse gas emissions, as does most biomass in agricultural regions.")
Faq.create!(question: "Is anybody already doing what you are wanting to do?", answer: "There are already people making ethanol (humans have made alcohol for 1000’s of years) for vehicle fuels.  And gasification technology has been used for decades.  However nobody has made the link to integrate these two pieces of equipment in a co-generation capacity.  Doing so will maximize efficiency both from an economic and environmental standpoint.")
Faq.create!(question: "Why is doing this a better idea than what is currently done?", answer: "What is currently being done (composting) is not only a contributor to greenhouse gasses, but it is wasting a perfectly good source of clean energy in the process. With increasing state and national demands for sustainable energy this waste stream is a “low hanging fruit”. It should complement a multi-pronged clean energy approach along with solar, wind, and geothermal solutions.")
Faq.create!(question: "Where would you build one of these plants?", answer: "As stated above, what is currently being done (composting) is not only a contributor to greenhouse gasses but it is ignoring a perfectly legitimate source of clean energy.  With increasing state and national demands for sustainable energy wine industry waste is a “low hanging fruit” and can complement a multi-faceted state and national clean energy strategy.")
Faq.create!(question: "Who would be your customers?", answer: "These are small distributed generation facilities that are placed in rural or semi rural environments next to existing industries that have consistent base load needs. Our demonstration scale facility is intended for the 76 acre site housing 10 wineries in Sebastopol, CA. This plant will be used to demonstrate what can be done at larger scale in other wine growing regions, starting with California’s Central Valley. Customers for advanced ethanol are petroleum companies who blend 10% of their gasoline stock with ethanol. Customers of our sustainable electricity are the co-located industries on-site.  Any/all excess electricity produced will help the local utility meet state carbon reduction standards.")
Faq.create!(question: "How do you make ethanol out of Pomace?", answer: "It is a fairly simple process involving the modern-day technology of an ancient process. Fuel grade ethanol is basically 198 proof alcohol, or 99.9% alcohol. Most cars can run on a blend of 10-15% ethanol with petroleum, and many newer cars can run on E85 or 85% ethanol. Alcohol is traditionally made by fermenting sugar from different organic materials.  Modern technology has advanced the field to include cellulosic methods and others.")
